### ISSUE TITLE
POET Automated Testing

### ISSUE THREAD

**Issue by mchurchward** [danielneis/moodle-search_elasticsearch#1]
Hi Daniel -
I also responded to your forum post here - https://moodle.org/mod/forum/discuss.php?d=227805#p1327742
At POET, we are working on developing and providing a suite of automated testing tools, as well as manual review, that plugin developers can use to help maintain the quality of their Moodle plugins, and promote them as solid and safe.
While these tools are still under development, we do have some of them working. For your benefit, I ran your plugin through what we have. You can see the results here - https://travis-ci.org/POETGroup/moodle-search_elasticsearch/jobs/116398112
At line 360, you can see the Moodle codechecker, that compares the code to the Moodle coding style standard. Getting this test to pass will help in the future.
At line 435, provided unit tests are executed. It would be good if you could build these tests as you build the plugin. Unit tests help verify new releases of the plugin.
At line 441, Behat tests are executed. Like unit tests, these tests help verify new releases and prevent regression errors.
I hope this helps, and don't hesitate to ask questions of me of make suggestions.
Thanks,
Mike

**Comment by mchurchward** [comment]
Hi Daniel -
I noticed you add a .travis.yml file to your branch.
I use a slightly modified one, and you can pull it from here if you are interested - https://github.com/POETGroup/moodle-search_elasticsearch/tree/POET_2015080602

**Comment by danielneis** [comment]
Hi, Mike

yes, thanks for the adapted version for work on the currente master.
I've been using the travis integration and the moodle-plugin-ci on some other plugins I've and it is really nice.

Kind regards,
Daniel
