### ISSUE TITLE
add_document method is missing the second argument

### ISSUE THREAD

**Issue by hcpss-banderson** [danielneis/moodle-search_elasticsearch#2]
When enabling the plugin on 3.1 I get:

Fatal error: Declaration of search_elasticsearch\engine::add_document() must be compatible with core_search\engine::add_document($document, $fileindexing = false) in /var/www/search/engine/elasticsearch/classes/engine.php on line 29

Looks like the add_document method is missing the second argument.

**Comment by danielneis** [comment]
ok, thanks for the report. fixed on master. best regards!
